[project]
name = "be"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.118.2",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "uvicorn[standard]>=0.37.0",
]
